/**
 * Palestinian market catalog seed data.
 * Categories and products commonly found in Baladi, Shufersal, Rami Levy, and local markets.
 * Includes Israeli/Palestinian brands: Tnuva, Osem, Elite, Strauss, Prigat, Tapuzina, Jordan,
 * Canaan, Al Ard, Nabulsi, Rana, Achva, Telma, Wissotsky, and international brands.
 */

export type CatalogCategorySeed = { title_en: string; title_ar: string; slug: string; sortOrder: number }
export type CatalogProductSeed = { title_en: string; title_ar: string; brand?: string; slug: string; defaultUnit: string }

export const CATALOG_CATEGORIES: CatalogCategorySeed[] = [
  { title_en: 'Fruits & Vegetables', title_ar: 'فواكه وخضروات', slug: 'fruits-vegetables', sortOrder: 0 },
  { title_en: 'Dairy & Eggs', title_ar: 'ألبان وبيض', slug: 'dairy-eggs', sortOrder: 1 },
  { title_en: 'Bakery & Pastries', title_ar: 'مخبوزات ومعجنات', slug: 'bakery-pastries', sortOrder: 2 },
  { title_en: 'Meat & Poultry', title_ar: 'لحوم ودواجن', slug: 'meat-poultry', sortOrder: 3 },
  { title_en: 'Beverages', title_ar: 'مشروبات', slug: 'beverages', sortOrder: 4 },
  { title_en: 'Snacks & Sweets', title_ar: 'وجبات خفيفة وحلويات', slug: 'snacks-sweets', sortOrder: 5 },
  { title_en: 'Canned & Pantry', title_ar: 'معلبات ومؤن', slug: 'canned-pantry', sortOrder: 6 },
  { title_en: 'Rice & Grains', title_ar: 'أرز وحبوب', slug: 'rice-grains', sortOrder: 7 },
  { title_en: 'Oil & Condiments', title_ar: 'زيوت وتوابل', slug: 'oil-condiments', sortOrder: 8 },
  { title_en: 'Cleaning & Household', title_ar: 'تنظيف ومنزل', slug: 'cleaning-household', sortOrder: 9 },
  { title_en: 'Personal Care', title_ar: 'العناية الشخصية', slug: 'personal-care', sortOrder: 10 },
  { title_en: 'Baby & Kids', title_ar: 'أطفال ورضع', slug: 'baby-kids', sortOrder: 11 },
  { title_en: 'Frozen Foods', title_ar: 'أطعمة مجمدة', slug: 'frozen-foods', sortOrder: 12 },
]

export const CATALOG_PRODUCTS_BY_CATEGORY: Record<string, CatalogProductSeed[]> = {
  'fruits-vegetables': [
    { title_en: 'Tomatoes', title_ar: 'طماطم', slug: 'tomatoes', defaultUnit: 'kg' },
    { title_en: 'Cucumbers', title_ar: 'خيار', slug: 'cucumbers', defaultUnit: 'kg' },
    { title_en: 'Potatoes', title_ar: 'بطاطا', slug: 'potatoes', defaultUnit: 'kg' },
    { title_en: 'Onions', title_ar: 'بصل', slug: 'onions', defaultUnit: 'kg' },
    { title_en: 'Lettuce', title_ar: 'خس', slug: 'lettuce', defaultUnit: 'piece' },
    { title_en: 'Eggplant', title_ar: 'باذنجان', slug: 'eggplant', defaultUnit: 'kg' },
    { title_en: 'Zucchini', title_ar: 'كوسا', slug: 'zucchini', defaultUnit: 'kg' },
    { title_en: 'Bell Peppers', title_ar: 'فلفل رومي', slug: 'bell-peppers', defaultUnit: 'kg' },
    { title_en: 'Carrots', title_ar: 'جزر', slug: 'carrots', defaultUnit: 'kg' },
    { title_en: 'Apples', title_ar: 'تفاح', slug: 'apples', defaultUnit: 'kg' },
    { title_en: 'Bananas', title_ar: 'موز', slug: 'bananas', defaultUnit: 'kg' },
    { title_en: 'Oranges', title_ar: 'برتقال', slug: 'oranges', defaultUnit: 'kg' },
    { title_en: 'Lemons', title_ar: 'ليمون', slug: 'lemons', defaultUnit: 'kg' },
    { title_en: 'Grapes', title_ar: 'عنب', slug: 'grapes', defaultUnit: 'kg' },
    { title_en: 'Watermelon', title_ar: 'بطيخ', slug: 'watermelon', defaultUnit: 'piece' },
    { title_en: 'Cabbage', title_ar: 'ملفوف', slug: 'cabbage', defaultUnit: 'piece' },
    { title_en: 'Dates', title_ar: 'تمر', slug: 'dates', defaultUnit: 'kg', brand: 'Canaan' },
    { title_en: 'Olives', title_ar: 'زيتون', slug: 'olives', defaultUnit: 'kg' },
  ],
  'dairy-eggs': [
    { title_en: 'Milk 3%', title_ar: 'حليب 3%', slug: 'milk-3', brand: 'Tnuva', defaultUnit: 'ml' },
    { title_en: 'Milk 1%', title_ar: 'حليب 1%', slug: 'milk-1', brand: 'Tnuva', defaultUnit: 'ml' },
    { title_en: 'Labaneh', title_ar: 'لبنة', slug: 'labaneh', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'White Cheese', title_ar: 'جبنة بيضاء', slug: 'white-cheese', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'Nabulsi Cheese', title_ar: 'جبنة نابلسية', slug: 'nabulsi-cheese', brand: 'Nabulsi', defaultUnit: 'piece' },
    { title_en: 'Yellow Cheese', title_ar: 'جبنة صفراء', slug: 'yellow-cheese', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'Butter', title_ar: 'زبدة', slug: 'butter', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'Yogurt', title_ar: 'لبن', slug: 'yogurt', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'Cottage Cheese', title_ar: 'جبنة قريش', slug: 'cottage-cheese', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'Eggs', title_ar: 'بيض', slug: 'eggs', brand: 'Free Range', defaultUnit: 'box' },
    { title_en: 'Cream Cheese', title_ar: 'كريمة الجبن', slug: 'cream-cheese', brand: 'Philadelphia', defaultUnit: 'pack' },
    { title_en: 'Sour Cream', title_ar: 'كريمة حامضة', slug: 'sour-cream', brand: 'Tnuva', defaultUnit: 'pack' },
    { title_en: 'Gvinah Levana', title_ar: 'جبنة بيضاء', slug: 'gvinah-levana', brand: 'Tnuva', defaultUnit: 'pack' },
  ],
  'bakery-pastries': [
    { title_en: 'Pita Bread', title_ar: 'خبز pita', slug: 'pita-bread', defaultUnit: 'pack' },
    { title_en: 'Laffa Bread', title_ar: 'خبز لافاش', slug: 'laffa-bread', defaultUnit: 'piece' },
    { title_en: 'Challah', title_ar: 'خبز حلاه', slug: 'challah', defaultUnit: 'piece' },
    { title_en: 'Whole Wheat Bread', title_ar: 'خبز أسمر', slug: 'whole-wheat-bread', defaultUnit: 'piece' },
    { title_en: 'Croissants', title_ar: 'كرواسون', slug: 'croissants', defaultUnit: 'piece' },
    { title_en: 'Bourekas', title_ar: 'بوريكاس', slug: 'bourekas', defaultUnit: 'piece' },
    { title_en: 'Kaak', title_ar: 'كعك', slug: 'kaak', defaultUnit: 'piece' },
    { title_en: 'Knafeh', title_ar: 'كنافة', slug: 'knafeh', defaultUnit: 'kg', brand: 'Nabulsi' },
    { title_en: 'Baklava', title_ar: 'بقلاوة', slug: 'baklava', defaultUnit: 'kg', brand: 'Nabulsi' },
    { title_en: 'Pizza', title_ar: 'بيتزا', slug: 'pizza', defaultUnit: 'piece' },
    { title_en: 'Bagels', title_ar: 'بيجل', slug: 'bagels', defaultUnit: 'piece' },
    { title_en: 'Tortilla', title_ar: 'تورتيجا', slug: 'tortilla', defaultUnit: 'pack' },
  ],
  'meat-poultry': [
    { title_en: 'Chicken Breast', title_ar: 'صدور دجاج', slug: 'chicken-breast', defaultUnit: 'kg' },
    { title_en: 'Chicken Thighs', title_ar: 'فخذ دجاج', slug: 'chicken-thighs', defaultUnit: 'kg' },
    { title_en: 'Ground Beef', title_ar: 'لحم مفروم', slug: 'ground-beef', defaultUnit: 'kg' },
    { title_en: 'Beef Steak', title_ar: 'ستيك لحم', slug: 'beef-steak', defaultUnit: 'kg' },
    { title_en: 'Lamb', title_ar: 'لحم خرفان', slug: 'lamb', defaultUnit: 'kg' },
    { title_en: 'Turkey', title_ar: 'ديك رومي', slug: 'turkey', defaultUnit: 'kg' },
  ],
  'beverages': [
    { title_en: 'Coca Cola', title_ar: 'كوكا كولا', slug: 'coca-cola', brand: 'Coca Cola', defaultUnit: 'bottle' },
    { title_en: 'Pepsi', title_ar: 'بيبسي', slug: 'pepsi', brand: 'Pepsi', defaultUnit: 'bottle' },
    { title_en: 'Schweppes', title_ar: 'شويبس', slug: 'schweppes', brand: 'Schweppes', defaultUnit: 'can' },
    { title_en: 'Tapuzina', title_ar: 'تابوزينا', slug: 'tapuzina', brand: 'Tapuzina', defaultUnit: 'bottle' },
    { title_en: 'Prigat', title_ar: 'بريغات', slug: 'prigat', brand: 'Prigat', defaultUnit: 'bottle' },
    { title_en: 'Jordan', title_ar: 'جوردن', slug: 'jordan', brand: 'Jordan', defaultUnit: 'bottle' },
    { title_en: 'Rana', title_ar: 'رانا', slug: 'rana-juice', brand: 'Rana', defaultUnit: 'bottle' },
    { title_en: 'Mey Eden', title_ar: 'مي إيدن', slug: 'mey-eden', brand: 'Mey Eden', defaultUnit: 'bottle' },
    { title_en: 'Neviot', title_ar: 'نيڤيوت', slug: 'neviot', brand: 'Neviot', defaultUnit: 'bottle' },
    { title_en: 'Nestle Water', title_ar: 'مياه نستله', slug: 'nestle-water', brand: 'Nestle', defaultUnit: 'bottle' },
    { title_en: 'Tampico', title_ar: 'تمبيكو', slug: 'tampico', brand: 'Tampico', defaultUnit: 'bottle' },
    { title_en: 'Red Bull', title_ar: 'ريد بول', slug: 'red-bull', brand: 'Red Bull', defaultUnit: 'can' },
    { title_en: 'Nescafe', title_ar: 'نسكافيه', slug: 'nescafe', brand: 'Nestle', defaultUnit: 'pack' },
    { title_en: 'Elite Coffee', title_ar: 'قهوة إيليت', slug: 'elite-coffee', brand: 'Elite', defaultUnit: 'pack' },
    { title_en: 'Lipton Tea', title_ar: 'شاي ليبتون', slug: 'lipton-tea', brand: 'Lipton', defaultUnit: 'pack' },
    { title_en: 'Wissotsky Tea', title_ar: 'شاي فيسوتسكي', slug: 'wissotsky-tea', brand: 'Wissotsky', defaultUnit: 'pack' },
  ],
  'snacks-sweets': [
    { title_en: 'Bamba', title_ar: 'بامبا', slug: 'bamba', brand: 'Osem', defaultUnit: 'pack' },
    { title_en: 'Bissli', title_ar: 'بيسلي', slug: 'bissli', brand: 'Osem', defaultUnit: 'pack' },
    { title_en: 'Parpar', title_ar: 'باربار', slug: 'parpar', brand: 'Telma', defaultUnit: 'pack' },
    { title_en: 'Shush', title_ar: 'شوش', slug: 'shush', brand: 'Strauss', defaultUnit: 'pack' },
    { title_en: 'Elite Chocolate', title_ar: 'شوكولاتة إيليت', slug: 'elite-chocolate', brand: 'Elite', defaultUnit: 'piece' },
    { title_en: 'Ramonim Cookies', title_ar: 'كوكيز رامونيم', slug: 'ramonim-cookies', brand: 'Elite', defaultUnit: 'pack' },
    { title_en: 'Krembo', title_ar: 'كريمبو', slug: 'krembo', brand: 'Elite', defaultUnit: 'piece' },
    { title_en: 'Chocolate Spread', title_ar: 'شوكولاتة للدهن', slug: 'chocolate-spread', brand: 'Elite', defaultUnit: 'pack' },
    { title_en: 'Halva', title_ar: 'حلوى', slug: 'halva', brand: 'Achva', defaultUnit: 'pack' },
    { title_en: 'Doritos', title_ar: 'دوريتوس', slug: 'doritos', brand: 'PepsiCo', defaultUnit: 'pack' },
    { title_en: 'Lays', title_ar: 'لايز', slug: 'lays', brand: 'PepsiCo', defaultUnit: 'pack' },
    { title_en: 'Kefli', title_ar: 'كيفلي', slug: 'kefli', brand: 'Elite', defaultUnit: 'pack' },
    { title_en: 'Bisli', title_ar: 'بيسلي', slug: 'bisli', brand: 'Osem', defaultUnit: 'pack' },
    { title_en: 'Bamba Duo', title_ar: 'بامبا دوبل', slug: 'bamba-duo', brand: 'Osem', defaultUnit: 'pack' },
    { title_en: 'Tnuva Chocolate Milk', title_ar: 'حليب شوكولاتة', slug: 'tnuva-chocolate-milk', brand: 'Tnuva', defaultUnit: 'bottle' },
  ],
  'canned-pantry': [
    { title_en: 'Tuna', title_ar: 'تونة', slug: 'tuna', brand: 'Starkist', defaultUnit: 'can' },
    { title_en: 'Hummus', title_ar: 'حمص', slug: 'hummus', brand: 'Achla', defaultUnit: 'pack' },
    { title_en: 'Hummus', title_ar: 'حمص', slug: 'hummus-achva', brand: 'Achva', defaultUnit: 'pack' },
    { title_en: 'Tomato Paste', title_ar: 'معجون طماطم', slug: 'tomato-paste', brand: 'Osem', defaultUnit: 'can' },
    { title_en: 'Chickpeas', title_ar: 'حمص حب', slug: 'chickpeas', brand: 'Osem', defaultUnit: 'can' },
    { title_en: 'Black Olives', title_ar: 'زيتون أسود', slug: 'black-olives', defaultUnit: 'can' },
    { title_en: 'Green Olives', title_ar: 'زيتون أخضر', slug: 'green-olives', defaultUnit: 'can' },
    { title_en: 'Pickles', title_ar: 'مخلل', slug: 'pickles', defaultUnit: 'jar' },
    { title_en: 'Beans', title_ar: 'فول', slug: 'beans', defaultUnit: 'can' },
    { title_en: 'Lentils', title_ar: 'عدس', slug: 'lentils', defaultUnit: 'pack' },
    { title_en: 'Foul', title_ar: 'فول', slug: 'foul', brand: 'Al Ard', defaultUnit: 'can' },
  ],
  'rice-grains': [
    { title_en: 'Basmati Rice', title_ar: 'أرز بسمتي', slug: 'basmati-rice', brand: 'Tilda', defaultUnit: 'pack' },
    { title_en: 'Jasmine Rice', title_ar: 'أرز ياسمين', slug: 'jasmine-rice', defaultUnit: 'pack' },
    { title_en: 'Couscous', title_ar: 'كسكس', slug: 'couscous', brand: 'Osem', defaultUnit: 'pack' },
    { title_en: 'Bulgur', title_ar: 'برغل', slug: 'bulgur', defaultUnit: 'pack' },
    { title_en: 'Freekeh', title_ar: 'فريكة', slug: 'freekeh', brand: 'Canaan', defaultUnit: 'pack' },
    { title_en: 'Pasta', title_ar: 'معكرونة', slug: 'pasta', brand: 'Barilla', defaultUnit: 'pack' },
    { title_en: 'Pasta', title_ar: 'معكرونة', slug: 'pasta-osem', brand: 'Osem', defaultUnit: 'pack' },
    { title_en: 'Spaghetti', title_ar: 'اسباجيتي', slug: 'spaghetti', brand: 'Barilla', defaultUnit: 'pack' },
  ],
  'oil-condiments': [
    { title_en: 'Olive Oil', title_ar: 'زيت زيتون', slug: 'olive-oil', defaultUnit: 'bottle' },
    { title_en: 'Olive Oil', title_ar: 'زيت زيتون', slug: 'olive-oil-canaan', brand: 'Canaan', defaultUnit: 'bottle' },
    { title_en: 'Olive Oil', title_ar: 'زيت زيتون', slug: 'olive-oil-al-ard', brand: 'Al Ard', defaultUnit: 'bottle' },
    { title_en: 'Sunflower Oil', title_ar: 'زيت دوار الشمس', slug: 'sunflower-oil', defaultUnit: 'bottle' },
    { title_en: 'Za\'atar', title_ar: 'زعتر', slug: 'zaatar', defaultUnit: 'pack' },
    { title_en: 'Za\'atar', title_ar: 'زعتر', slug: 'zaatar-canaan', brand: 'Canaan', defaultUnit: 'pack' },
    { title_en: 'Tahini', title_ar: 'طحينة', slug: 'tahini', brand: 'Achva', defaultUnit: 'bottle' },
    { title_en: 'Tahini', title_ar: 'طحينة', slug: 'tahini-al-noor', brand: 'Al Noor', defaultUnit: 'bottle' },
    { title_en: 'Mayonnaise', title_ar: 'مايونيز', slug: 'mayonnaise', brand: 'Hellmann\'s', defaultUnit: 'bottle' },
    { title_en: 'Ketchup', title_ar: 'كاتشب', slug: 'ketchup', brand: 'Heinz', defaultUnit: 'bottle' },
    { title_en: 'Salt', title_ar: 'ملح', slug: 'salt', defaultUnit: 'pack' },
    { title_en: 'Black Pepper', title_ar: 'فلفل أسود', slug: 'black-pepper', defaultUnit: 'pack' },
    { title_en: 'Cumin', title_ar: 'كمون', slug: 'cumin', defaultUnit: 'pack' },
  ],
  'cleaning-household': [
    { title_en: 'Dish Soap', title_ar: 'صابون غسيل الصحون', slug: 'dish-soap', brand: 'Fairy', defaultUnit: 'bottle' },
    { title_en: 'Laundry Detergent', title_ar: 'مسحوق غسيل', slug: 'laundry-detergent', brand: 'Ariel', defaultUnit: 'box' },
    { title_en: 'Toilet Paper', title_ar: 'ورق تواليت', slug: 'toilet-paper', defaultUnit: 'pack' },
    { title_en: 'Paper Towels', title_ar: 'مناشف ورقية', slug: 'paper-towels', defaultUnit: 'pack' },
    { title_en: 'Garbage Bags', title_ar: 'أكياس نفايات', slug: 'garbage-bags', defaultUnit: 'pack' },
  ],
  'personal-care': [
    { title_en: 'Shampoo', title_ar: 'شامبو', slug: 'shampoo', brand: 'Head & Shoulders', defaultUnit: 'bottle' },
    { title_en: 'Soap', title_ar: 'صابون', slug: 'soap', defaultUnit: 'piece' },
    { title_en: 'Olive Oil Soap', title_ar: 'صابون زيت زيتون', slug: 'olive-oil-soap', brand: 'Nabulsi', defaultUnit: 'piece' },
    { title_en: 'Toothpaste', title_ar: 'معجون أسنان', slug: 'toothpaste', brand: 'Colgate', defaultUnit: 'piece' },
    { title_en: 'Deodorant', title_ar: 'مزيل عرق', slug: 'deodorant', brand: 'Rexona', defaultUnit: 'piece' },
    { title_en: 'Razor', title_ar: 'ماكينة حلاقة', slug: 'razor', defaultUnit: 'piece' },
  ],
  'baby-kids': [
    { title_en: 'Baby Formula', title_ar: 'حليب أطفال', slug: 'baby-formula', brand: 'Similac', defaultUnit: 'can' },
    { title_en: 'Diapers', title_ar: 'حفاضات', slug: 'diapers', brand: 'Pampers', defaultUnit: 'pack' },
    { title_en: 'Baby Wipes', title_ar: 'مناديل أطفال', slug: 'baby-wipes', defaultUnit: 'pack' },
  ],
  'frozen-foods': [
    { title_en: 'Frozen Vegetables', title_ar: 'خضروات مجمدة', slug: 'frozen-vegetables', defaultUnit: 'pack' },
    { title_en: 'Ice Cream', title_ar: 'آيس كريم', slug: 'ice-cream', brand: 'Ben & Jerry\'s', defaultUnit: 'pack' },
    { title_en: 'Ice Cream', title_ar: 'آيس كريم', slug: 'ice-cream-strauss', brand: 'Strauss', defaultUnit: 'pack' },
    { title_en: 'Frozen Pizza', title_ar: 'بيتزا مجمدة', slug: 'frozen-pizza', defaultUnit: 'piece' },
    { title_en: 'Frozen Fries', title_ar: 'بطاطا مجمدة', slug: 'frozen-fries', defaultUnit: 'pack' },
  ],
}
