import { type SchemaTypeDefinition } from 'sanity'
import { tenantType } from './tenant'
import { categoryType } from './category'
import { productType } from './product'
import { restaurantInfoType } from './restaurantInfo'
import { aboutUsType } from './aboutUs'
import { platformAreaType } from './platformArea'
import { driverType } from './driver'
import { tenantDriverType } from './tenantDriver'
import { platformUserType } from './platformUser'
import { orderType } from './order'
import { customerType } from './customer'
import { heroBannerType } from './heroBanner'
import { bannerSettingsType } from './bannerSettings'
import { businessCategoryType } from './businessCategory'
import { businessSubcategoryType } from './businessSubcategory'
import { reportType } from './report'
import { tenantTransferRequestType } from './tenantTransferRequest'
import { suspendedContactType } from './suspendedContact'
import { customerPushSubscriptionType } from './customerPushSubscription'
import { tenantTableType } from './tenantTable'
import { tenantStaffType } from './tenantStaff'
import { userPushSubscriptionType } from './userPushSubscription'
import { tableServiceRequestType } from './tableServiceRequest'
import { otpVerificationType } from './otpVerification'
import { broadcastHistoryType } from './broadcastHistory'
import { whatsappMessageType } from './whatsappMessage'
import { bopProcessedPaymentType } from './bopProcessedPayment'
import { catalogCategoryType } from './catalogCategory'
import { catalogProductType } from './catalogProduct'
import { masterCatalogProductType } from '../../schemas/masterCatalog'
import { scrollAnimationType } from './scrollAnimation'

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [tenantType, categoryType, catalogCategoryType, catalogProductType, masterCatalogProductType, productType, restaurantInfoType, aboutUsType, platformAreaType, driverType, tenantDriverType, platformUserType, orderType, customerType, customerPushSubscriptionType, userPushSubscriptionType, heroBannerType, bannerSettingsType, businessCategoryType, businessSubcategoryType, reportType, tenantTransferRequestType, suspendedContactType, tenantTableType, tenantStaffType, tableServiceRequestType, otpVerificationType, broadcastHistoryType, whatsappMessageType, bopProcessedPaymentType, scrollAnimationType],
}
