import { defineField, defineType } from 'sanity'

export const orderType = defineType({
  name: 'order',
  title: 'Order',
  type: 'document',
  fields: [
    defineField({
      name: 'site',
      title: 'Site',
      type: 'reference',
      to: [{ type: 'tenant' }],
      description: 'Which business/site this order belongs to',
    }),
    defineField({
      name: 'orderNumber',
      title: 'Order Number',
      type: 'string',
      readOnly: true,
      description: 'Auto-generated unique order number',
    }),
    defineField({
      name: 'orderType',
      title: 'Order Type',
      type: 'string',
      options: {
        list: [
          { title: 'Receive in Person', value: 'receive-in-person' },
          { title: 'Dine-in', value: 'dine-in' },
          { title: 'Delivery', value: 'delivery' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Order Status',
      type: 'string',
      options: {
        list: [
          { title: '🆕 New', value: 'new' },
          { title: '👍 Acknowledged', value: 'acknowledged' },
          { title: '👨‍🍳 Preparing', value: 'preparing' },
          { title: '⏳ Waiting for Delivery', value: 'waiting_for_delivery' },
          { title: '🚗 Driver is on the way to the restaurant', value: 'driver_on_the_way' },
          { title: '📦 Driver on the way to you', value: 'out-for-delivery' },
          { title: '✅ Delivered & COMPLETED', value: 'completed' },
          { title: '🍽️ Served (Dine-in)', value: 'served' },
          { title: '❌ Cancelled', value: 'cancelled' },
          { title: '💰 Refunded', value: 'refunded' },
        ],
      },
      initialValue: 'new',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'customer',
      title: 'Customer',
      type: 'reference',
      to: [{ type: 'customer' }],
      description: 'Registered customer (Clerk user). Set when order is placed.',
      readOnly: true,
    }),
    defineField({
      name: 'customerName',
      title: 'Customer Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    // Dine-in only: table number (receive-in-person has no table)
    defineField({
      name: 'tableNumber',
      title: 'Table Number',
      type: 'string',
      description: 'For dine-in orders only',
      hidden: ({ parent }) => parent?.orderType !== 'dine-in',
    }),
    // Customer phone / WhatsApp (required for dine-in and receive-in-person for contact; also used for delivery)
    defineField({
      name: 'customerPhone',
      title: 'Customer Phone / WhatsApp',
      type: 'string',
      description: 'Required for dine-in and receive-in-person (tenant may contact customer). Also used for delivery.',
    }),
    defineField({
      name: 'deliveryArea',
      title: 'Delivery Area',
      type: 'reference',
      to: [{ type: 'area' }],
      description: 'Selected delivery area',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'deliveryAddress',
      title: 'Delivery Address Details',
      type: 'text',
      rows: 3,
      description: 'Specific location details for delivery',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'deliveryLat',
      title: 'Delivery latitude',
      type: 'number',
      description: 'Customer shared location (for driver navigation). Optional.',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'deliveryLng',
      title: 'Delivery longitude',
      type: 'number',
      description: 'Customer shared location (for driver navigation). Optional.',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'deliveryFee',
      title: 'Delivery Fee',
      type: 'number',
      description: 'Delivery fee charged for this order',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'deliveryJourneyLog',
      title: 'Delivery Journey Log',
      type: 'array',
      description: 'Log of driver locations and events during the delivery',
      of: [
        {
          type: 'object',
          name: 'journeyLogEntry',
          fields: [
            { name: 'at', type: 'datetime', title: 'Timestamp' },
            { name: 'lat', type: 'number', title: 'Latitude' },
            { name: 'lng', type: 'number', title: 'Longitude' },
            { name: 'label', type: 'string', title: 'Event Label' },
            { name: 'source', type: 'string', title: 'Source (e.g. driver, system)' },
          ],
        },
      ],
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
      readOnly: true,
    }),
    defineField({
      name: 'assignedDriver',
      title: 'Assigned Driver',
      type: 'reference',
      to: [{ type: 'driver' }],
      description: 'Driver assigned to deliver this order',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'deliveryRequestedAt',
      title: 'Delivery requested at',
      type: 'datetime',
      description: 'When set, order is shown to online drivers in the same area. Cleared when a driver accepts.',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'lastDeliveryRequestPingAt',
      title: 'Last delivery request ping at',
      type: 'datetime',
      readOnly: true,
      hidden: true,
      description: 'Updated by the retry-delivery-requests cron job each time it re-sends push to online drivers (every 3 min).',
    }),
    defineField({
      name: 'businessWhatsappNotifiedAt',
      title: 'Business WhatsApp Notified At',
      type: 'datetime',
      readOnly: true,
      hidden: true,
      description: 'When the business was notified via WhatsApp about an unaccepted order.',
    }),
    defineField({
      name: 'driversWhatsappNotifiedAt',
      title: 'Drivers WhatsApp Notified At',
      type: 'datetime',
      readOnly: true,
      hidden: true,
      description: 'When the available drivers in the city were notified via WhatsApp about this unaccepted delivery.',
    }),
    defineField({
      name: 'driversWhatsappNotifiedCount',
      title: 'Drivers WhatsApp Notified Count',
      type: 'number',
      readOnly: true,
      hidden: true,
      description: 'Number of times drivers were notified via WhatsApp (max 3).',
    }),
    defineField({
      name: 'tenantNewOrderPushSent',
      title: 'Tenant New Order Push Sent',
      type: 'boolean',
      readOnly: true,
      hidden: true,
      description: 'Whether the new order FCM push notification has been sent to the business owner and staff.',
    }),
    defineField({
      name: 'declinedByDriverIds',
      title: 'Declined by drivers',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'driver' }] }],
      description: 'Drivers who declined this order; they will not see it again in the pool unless the restaurant assigns it to them.',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
      readOnly: true,
    }),
    // Order items
    defineField({
      name: 'items',
      title: 'Order Items',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'orderItem',
          fields: [
            defineField({
              name: 'product',
              title: 'Product',
              type: 'reference',
              to: [{ type: 'product' }],
            }),
            defineField({
              name: 'productName',
              title: 'Product Name',
              type: 'string',
              description: 'Stored name at time of order',
            }),
            defineField({
              name: 'quantity',
              title: 'Quantity',
              type: 'number',
              validation: (Rule) => Rule.required().min(1),
            }),
            defineField({
              name: 'price',
              title: 'Unit Price',
              type: 'number',
              description: 'Price per unit at time of order',
            }),
            defineField({
              name: 'total',
              title: 'Total',
              type: 'number',
              description: 'Total price for this item',
            }),
            defineField({
              name: 'notes',
              title: 'Special Requests',
              type: 'text',
              rows: 2,
            }),
            defineField({
              name: 'addOns',
              title: 'Add-ons',
              type: 'string',
              description: 'Selected add-ons for this item',
            }),
          ],
          preview: {
            select: {
              name: 'productName',
              quantity: 'quantity',
              total: 'total',
            },
            prepare({ name, quantity, total }) {
              return {
                title: `${quantity}x ${name}`,
                subtitle: `${total?.toFixed(2) || 0} ₪`,
              }
            },
          },
        },
      ],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'subtotal',
      title: 'Subtotal',
      type: 'number',
      description: 'Total before delivery fee',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'totalAmount',
      title: 'Total Amount',
      type: 'number',
      description: 'Total including delivery fee',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      initialValue: 'ILS',
    }),
    defineField({
      name: 'createdAt',
      title: 'Order Date & Time',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'scheduledFor',
      title: 'Scheduled For',
      type: 'datetime',
      description: 'When set, this is an upfront/scheduled order to be prepared for this date/time.',
    }),
    defineField({
      name: 'scheduleEditHistory',
      title: 'Schedule Edit History',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'scheduleEdit',
          fields: [
            { name: 'previousScheduledFor', type: 'datetime', title: 'Previous Scheduled For' },
            { name: 'changedAt', type: 'datetime', title: 'Changed At' }
          ]
        }
      ],
      description: 'History of changes to the scheduled time',
      readOnly: true,
    }),
    defineField({
      name: 'acknowledgedAt',
      title: 'Acknowledged At',
      type: 'datetime',
      description: 'When the restaurant acknowledged a scheduled order',
    }),
    defineField({
      name: 'notifyAt',
      title: 'Notify At',
      type: 'datetime',
      description: 'When the business should be reminded to start preparing this scheduled order',
    }),
    defineField({
      name: 'reminderSent',
      title: 'Reminder Sent',
      type: 'boolean',
      description: 'Whether the reminder notification has been successfully sent',
    }),
    defineField({
      name: 'preparedAt',
      title: 'Prepared At',
      type: 'datetime',
      description: 'When the order was marked as preparing or waiting for delivery',
    }),
    defineField({
      name: 'driverAcceptedAt',
      title: 'Driver Accepted At',
      type: 'datetime',
      description: 'When the driver accepted or was assigned the order',
    }),
    defineField({
      name: 'driverPickedUpAt',
      title: 'Driver Picked Up At',
      type: 'datetime',
      description: 'When the driver picked up the order (out for delivery)',
    }),
    defineField({
      name: 'estimatedDeliveryMinutes',
      title: 'Estimated Delivery Minutes',
      type: 'number',
      description: 'Estimated minutes from pickup to customer (OSRM route + 5 min buffer). Set when driver picks up.',
      readOnly: true,
      hidden: ({ parent }) => parent?.orderType !== 'delivery',
    }),
    defineField({
      name: 'completedAt',
      title: 'Completed At',
      type: 'datetime',
      description: 'When the order was completed',
    }),
    defineField({
      name: 'cancelledAt',
      title: 'Cancelled At',
      type: 'datetime',
      description: 'When the order was cancelled or refunded (by business or customer)',
    }),
    defineField({
      name: 'driverCancelledAt',
      title: 'Driver Cancelled At',
      type: 'datetime',
      description: 'When a driver cancelled the delivery (order goes back to preparing, available for other drivers)',
      hidden: ({ parent }) => parent?.orderType === 'dine-in' || parent?.orderType === 'receive-in-person',
    }),
    defineField({
      name: 'notes',
      title: 'Internal Notes',
      type: 'text',
      rows: 3,
      description: 'Internal notes for restaurant staff',
    }),
    defineField({
      name: 'itemsUpdatedAt',
      title: 'Items updated at',
      type: 'datetime',
      description: 'Set when business updates order items (add/remove). Driver must reconfirm.',
      hidden: ({ parent }) => parent?.orderType !== 'delivery',
    }),
    defineField({
      name: 'driverReconfirmedAt',
      title: 'Driver reconfirmed at',
      type: 'datetime',
      description: 'When driver reconfirmed after items were updated.',
      hidden: ({ parent }) => parent?.orderType !== 'delivery',
    }),
    defineField({
      name: 'trackingToken',
      title: 'Tracking token',
      type: 'string',
      description: 'Secret token for customer order tracking URL. Generated on order create.',
      readOnly: true,
    }),
    defineField({
      name: 'customerPushSubscription',
      title: 'Customer push subscription',
      type: 'object',
      description: 'Web Push subscription for order status notifications (set when customer enables on tracking page).',
      readOnly: true,
      hidden: ({ document }) => !document?.customerPushSubscription,
      fields: [
        { name: 'endpoint', type: 'string', title: 'Endpoint' },
        { name: 'p256dh', type: 'string', title: 'p256dh' },
        { name: 'auth', type: 'string', title: 'auth' },
      ],
    }),
    defineField({
      name: 'customerFcmToken',
      title: 'Customer FCM token',
      type: 'string',
      description: 'Firebase Cloud Messaging token for order status push (when customer enables on tracking page).',
      readOnly: true,
      hidden: true,
    }),
    // Dine-in: customer requested waiter or check (triggers ring on restaurant dashboard)
    defineField({
      name: 'customerRequestType',
      title: 'Customer request type',
      type: 'string',
      options: { list: [{ title: 'Call waiter', value: 'call_waiter' }, { title: 'Request check', value: 'request_check' }] },
      description: 'Set when dine-in customer taps "Call waiter" or "Ask for check" on tracking page.',
      hidden: ({ parent }) => parent?.orderType !== 'dine-in',
    }),
    defineField({
      name: 'customerRequestPaymentMethod',
      title: 'Requested payment method',
      type: 'string',
      options: { list: [{ title: 'Cash', value: 'cash' }, { title: 'Card', value: 'card' }] },
      description: 'When customer requested check, preferred payment method.',
      hidden: ({ parent }) => parent?.orderType !== 'dine-in',
    }),
    defineField({
      name: 'customerRequestedAt',
      title: 'Customer requested at',
      type: 'datetime',
      description: 'When the customer requested waiter or check (triggers notification at restaurant).',
      hidden: ({ parent }) => parent?.orderType !== 'dine-in',
    }),
    defineField({
      name: 'customerRequestAcknowledgedAt',
      title: 'Customer request acknowledged at',
      type: 'datetime',
      description: 'When staff acknowledged the table request (stops notification).',
      hidden: ({ parent }) => parent?.orderType !== 'dine-in',
    }),
    // Optional tip (customer can add on tracking page)
    defineField({
      name: 'tipPercent',
      title: 'Tip percentage',
      type: 'number',
      description: 'Tip percentage chosen by customer (e.g. 10).',
    }),
    defineField({
      name: 'tipAmount',
      title: 'Tip amount',
      type: 'number',
      description: 'Tip amount in order currency.',
    }),
    defineField({
      name: 'tipSentToDriver',
      title: 'Tip sent to driver',
      type: 'boolean',
      description: 'Whether the customer has shared their tip intention with the driver.',
    }),
    defineField({
      name: 'tipSentToDriverAt',
      title: 'Tip sent to driver at',
      type: 'datetime',
      description: 'When the customer shared the tip with the driver.',
      readOnly: true,
    }),
    defineField({
      name: 'tipConfirmedAfterCountdown',
      title: 'Tip confirmed after countdown',
      type: 'boolean',
      description: 'When countdown expired, whether the customer chose to keep the tip.',
    }),
    defineField({
      name: 'tipIncludedInTotal',
      title: 'Tip included in total',
      type: 'boolean',
      description: 'Customer confirmed the tip should be added to the total amount the driver collects.',
    }),
    defineField({
      name: 'tipRemovedByDriver',
      title: 'Tip removed by driver',
      type: 'boolean',
      description: 'Driver chose to remove the tip from the total before completing the order.',
    }),
    defineField({
      name: 'driverArrivedAt',
      title: 'Driver arrived at',
      type: 'datetime',
      description: 'When the driver confirmed arrival at the customer location (within 100m).',
      hidden: ({ parent }) => parent?.orderType !== 'delivery',
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      orderNumber: 'orderNumber',
      customerName: 'customerName',
      orderType: 'orderType',
      status: 'status',
      totalAmount: 'totalAmount',
      currency: 'currency',
      createdAt: 'createdAt',
      siteLogo: 'site.businessLogo',
    },
    prepare(selection) {
      const { orderNumber, customerName, orderType, status, totalAmount, currency, createdAt, siteLogo } = selection ?? {}
      const date = typeof createdAt === 'string' ? new Date(createdAt).toLocaleDateString() : ''
      const typeIcon = orderType === 'delivery' ? '🚗' : '🍽️'
      const amount = typeof totalAmount === 'number' ? `${totalAmount.toFixed(2)} ${currency || ''}` : '—'
      const result = {
        title: `${typeIcon} #${orderNumber || 'New'} · ${customerName || '—'}`,
        subtitle: `${status || '—'} · ${amount} · ${date}`,
      }
      if (siteLogo) (result as { title: string; subtitle: string; media?: unknown }).media = siteLogo
      return result
    },
  },
  orderings: [
    {
      title: 'Newest First',
      name: 'createdAtDesc',
      by: [{ field: 'createdAt', direction: 'desc' }],
    },
    {
      title: 'Oldest First',
      name: 'createdAtAsc',
      by: [{ field: 'createdAt', direction: 'asc' }],
    },
  ],
})
